spring.application.name=SecondBrainAI

# Neo4j Configuration
spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

# JWT Secret
jwt.secret=7d425b7d60e7161b9b89c7c00e12b7a421689ea5286be62b1a6c40a586d11f7c
jwt.expirationMs=86400000

# Server
server.port=8080
gemini.api.key=${GEMINI_API_KEY}
