spring.application.name=SecondBrainAI

# Neo4j Configuration
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=password

# JWT Secret
jwt.secret=7d425b7d60e7161b9b89c7c00e12b7a421689ea5286be62b1a6c40a586d11f7c
jwt.expirationMs=86400000

# Server
server.port=8080
gemini.api.key=AIzaSyCr2xGy6B8zDh6buhy90i8dJae9bYQKyHA
